### ISSUE TITLE
Announce instructions for touch support only if it is enabled

### ISSUE THREAD

**Issue by ebonow** [mynamesleon/aria-autocomplete#23]
If a user is using assistive technology without touch support, it would be beneficial to skip the directions on how to use with touch support

**Comment by ebonow** [comment]
Retracting this. There may be assistive technologies which that would not necessarily be touch reliant but might benefit from extra instructions (ie: Kinect)

**Comment by mynamesleon** [comment]
Sorry for my delayed reply. I've been quite busy with work lately.

Yes I left the announcement in partly for that reason, but also because detecting touch devices can be awkward - it's reliable in most cases, but I found a few edge cases in the past. So I opted to have it there, and not need it, rather than need it and not have it.
