### ISSUE TITLE
deleteAll method

### ISSUE THREAD

**Issue by ooplala** [mynamesleon/aria-autocomplete#33]
Hi, 
Thank you for this module! It does everything I need <3

I made a form that has a "clear all" button for clearing all values in my input fields (most are not using autocomplete). I would like this button to do the same thing as the "Delete All" button that is created with the deleteAllControl option. Is there a method defined for this?
All I can find are the functions "close", "destroy", "disable", "enable", "filter" and "open". If I use destroy() and recreate my autocomplete, it returns to the same state (e.g. with its previous selections).

Best regards,

**Comment by mynamesleon** [comment]
Hi @ooplala - I'm glad you're finding it useful :)

That's a very good point, and something I clearly missed. This should definitely be added to the API. 

Are you using the module to progressively enhance existing form elements by the way? Just thinking that I'll need to consider this a bit more broadly too... when the module is used to progressively enhance a select or checkbox list, it doesn't currently listen for the reset event on the parent form element to update based on the new underlying element(s) values - so that's something I need to add too.

**Comment by mynamesleon** [comment]
I'm glad you've found a solution that works for you at the moment @ooplala. In a standard 'reset' case (returning all form elements to their _starting_ values) just destroying and re-initialising the autocomplete does arguably make sense, and gives people full control of the re-initialised state. 

I'd still like to get `delete()` and `deleteAll()` methods added to the API though, as they could definitely be useful
