### ISSUE TITLE
Handling focus on input: onDelete executed whilst deletion is not complete

### ISSUE THREAD

**Issue by spryah** [mynamesleon/aria-autocomplete#37]
Hello @mynamesleon, thank you for your work on this very useful tool.

Following the issue #9 in which it was requested to move the focus back on the input element after deleting the last selected item.
I have taken good note of your concerns for the users who would want to delete only a few items. However, in our projects, we still find ourselves in need of moving the focus back on the input element after deleting all the selected items.

We chose to perform this action using the `onDelete` callback, but it turns out that this callback is executed in the middle of the delete actions, and not at the end as we expected. It resulted in the focus being moved to the input before the deleting action is completed, and so the input receives the `Enter` key action, which triggers the form submission.

Here are a few solutions we've investigated to overcome this:

- provide a boolean option to move the focus to the input element after the last selected element is deleted, instead of letting it go back to the body, then to the next available element?
- always execute `event.preventDefault` when the input receives the `Enter` key action?
- call `onDelete` after the delete action is completely performed: could we consider a `beforeDelete` / `afterDelete` callback?

What do you think?

Thank you in advance

**Comment by mynamesleon** [comment]
Hi @spryah. Sorry for my delayed reply to this - work has been busy lately! Regarding your suggestions:

1. this is certainly viable (although it might be quite an obscure option to name! 😆), but it may still have a problem... (see (3) below)
2. I intentionally didn't bind keypress events and execute `event.preventDefault()` for the `Enter` key on the input because I didn't want to interfere with the default form submission behaviour for inputs.
3. I'm not sure this would fix it. The `Enter` key behaviour is bound to keydown events, and firing `onDelete` or `afterDelete` as part of that, and then you immediately moving focus to the input, would still cause the form submission to happen because the `Enter` keydown may still fire on the input (and the keypress and keyup presumably still would as well).

My suggestion would be to do exactly as you're doing, but to bind keypress listeners onto the input and execute `event.preventDefault()` yourself. Please let me know if that seems suitable to you?

(If you wanted the equivalent of an `afterDelete` by the way, you could still use the existing `onDelete` but execute your focus moving code inside a `setTimeout` that has no delay. That would cause your code to execute at the end of the call stack)

**Comment by spryah** [comment]
Hello @mynamesleon, thank you for your reply!

We ended up executing our code inside a `setTimeout` and it did the work; but we were looking for a "cleaner" way to achieve this result 😅
I guess that's that!
