### ISSUE TITLE
Accessibility corrections

### ISSUE THREAD

**Issue by mh-nichts** [mynamesleon/aria-autocomplete#9]
Hello,

As my colleague Pascal already said, thanks for this very good and useful plug-in.

We had an exchange with an accessibility expert about it, and he listed some corrections to do : 
- span.aria-autocomplete__selected (multiple selection tags) : on click (deletion), put the focus back on the input field
- ul.aria-autocomplete__list : add aria-describedby="xxx" where xxx = label id
- span.aria-autocomplete__sr-assistance :
  - replace with a "p" instead of span
  - mask with display none
- span.aria-autocomplete__sr-announcements
  - replace with a "p" instead of span
  - empty when the suggestions list closes
  - empty after 2s when deleting an item, if no other action changes its content in the meantime

We're going to try and fix some of this things by ourselves, and maybe we'll submit some PR, but feel free to give your insights on these points !
Thanks in advance.

**Comment by mynamesleon** [comment]
Thank you. I'm glad you're finding it useful :). 

Sorry for my delayed reply to this - these issues got buried within my other emails!

To address each of the points in turn:
1. re deleting items in multiple selection mode: the focus is currently left up to the browser when an item is deleted partly for predictability (as I generally dislike modifying default browser behaviour), and to make it easier for users to delete multiple items. The other issue you've raised about a delete all button would partially handle the latter case, but it still wouldn't apply to multiple specific deletions (e.g. when a user has 10 selected items, and wants to delete items 3 and 8). So in my own testing, I found that leaving the focus position up to the browser to handle was the best compromise.
2. re aria-describedby on the list: that definitely seems like a worthwhile addition. I didn't actually notice any specific benefit to this with the devices/software I tested, so I removed it in the end. But there's certainly no harm in it being there.
3. re the sr-assistance element: did your colleague notice any specific benefit to it being a paragraph element rather than a span? I chose to make it a span mostly because that's an inline element, whereas a block element implies some level of independence in the DOM from the input it relates to - I also didn't notice any difference in my own testing. Re hiding it, I was relying on the sr-only class added to it to leave it visible to screen readers, so that users could still find it when navigating the page if they wanted to. But that is probably unnecessary, particularly with the adjustment suggested in one of your other issues, of always keeping it linked to the input.
4. re the sr-announcements element: again, I'm curious what benefit your colleague found from making it a paragraph element? As for clearing it, I did actually experiment with clearing it after a small delay, but I found that it sometimes cancelled the announcement - I can't remember which screen reader software that was with though, but I think it may have been an older ChromeVox version - I'll have to retest that. Clearing it when the list closes definitely makes sense though. I'll need to also experiment with clearing it after deletions in some way, as it's used in that scenario as well.

**Comment by mynamesleon** [comment]
@mh-nichts I've made my adjustments for these, but I've opted for what might be considered compromises.

1. re deleting a selected item - instead of returning focus to the input, I'm moving focus to the next available option. This is to make it easier for users to make consecutive deletions. If there are no items left, I'm not manually moving the focus. This is to avoid clashing with how the browser would handle focus by default in this case, and potentially causing confusion (particularly as the elements representing selected items sit after the autocomplete input in the DOM). This is especially relevant for other assistive technologies that might trigger this interaction for a user (e.g. speech recognition software).
This also specifically only happens when clicking, or using enter, on one of these items. Notably there are other cases that trigger deletions (such as backspace, or when blurring off of the input in single select mode with invalid selection text in the input)
2. Added
3. Changed
4. I recognise that this is very much a valid suggestion, but I'm conscious of issues I discovered with this in the past, as well as the possibility of the announcements being lost. So as a compromise, I've added an `srAutoClear` option to enable this. It defaults to `false` so that the existing behaviour is unchanged, but can be set to true for a 2 second delay, or if during testing someone finds that to be too short a delay, it can be set to a custom milisecond delay.
Notably however, it auto-clears only after announcements have been made. The auto-clear doesn't happen when the list closes, as that could interfere with the announcement that's made after a selection.

**Comment by mynamesleon** [comment]
@mh-nichts I've done some additional testing of clearing the announcements element after a delay (using NVDA on Windows (testing both Chromium and Firefox), VoiceOver on MacOS, and on Android) and I'm happy to set this as the default now, particularly as I've created an option for this, so people can disable it if they find that necessary.

So my next update will include a default value for the `srAutoClear` option. I'm going to set it to `5000` by default just in case, but this can of course be set to `2000` if preferred, as per your original comment (if you choose to use my maintained version of the plugin instead of your own fork of course).

**Comment by mh-nichts** [comment]
Hello,
Thank you for all your replies and your recent work ! I'm going to try and process all the subjects.

1. I understand the dilemna about moving the focus : I think moving to the next selected element is also a valid choice. 
But as you mention, when there is no element left, the handling is still left to the browser. That means the focus can be completely lost (back at the top of page for example), and it's this kind of situation that we wanted to address in the first place. 
I think in this case, moving it back to the input seems the most adequate ?
2. Yes it's only a small addition, thanks.
3. Indeed when always linked to the input, it doesn't need to stay available as sr-only, hence the display none.
4. Handling it as an option is a great choice, thanks ! 
I also noticed that clearing it on close would interfere with the announcement made after a selection, so we didn't implement it in the end : the auto-clear after 2s was enough. 

Regarding your questions on 3 & 4 :
-  using a p instead of span : as far as I know, it's to identify this content as a block of text, with the correct semantics (span has no real semantic) so it's interpreted correctly by the assistive technologies
- hiding/removing these announcements : I think it's to avoid this content being returned by assistive technologies while parsing the page, when it's not yet, or not relevant anymore
But I might let our accessibility expert @goetsu confirm these.

**Comment by mynamesleon** [comment]
@mh-nichts my main concern with returning the focus to the input after deleting the last selected item is that, depending on the chosen options, this can force the user to need to move through several of the same elements again.

For example, consider if you set the `minLength` option to `0`, and have the `showAllControl` set to `true`. After deleting the last selected item, if the library were to automatically return the focus to the input, that will cause an additional search to happen (and the consequent screen reader announcements for the number of results and the assistive text). And the user would then have to tab past the show all control and the currently displaying list just to get back to where they were.
